// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: da_sanwang_broker_processlog_qhy_rank_daily.proto

package com.example.springboot.loopload;

public final class DaSanwangBrokerProcesslogQhyRankDaily {
  private DaSanwangBrokerProcesslogQhyRankDaily() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface da_sanwang_broker_processlog_qhy_rank_dailyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 _broker_id = 1;</code>
     * @return The brokerId.
     */
    long getBrokerId();

    /**
     * <code>int32 _stores_id = 2;</code>
     * @return The storesId.
     */
    int getStoresId();

    /**
     * <code>int32 _real_store_id = 3;</code>
     * @return The realStoreId.
     */
    int getRealStoreId();

    /**
     * <code>int32 _store_broker_num = 4;</code>
     * @return The storeBrokerNum.
     */
    int getStoreBrokerNum();

    /**
     * <code>int32 _company_broker_num = 5;</code>
     * @return The companyBrokerNum.
     */
    int getCompanyBrokerNum();

    /**
     * <code>int32 _city_broker_num = 6;</code>
     * @return The cityBrokerNum.
     */
    int getCityBrokerNum();

    /**
     * <code>int32 _first_sku_new_today = 7;</code>
     * @return The firstSkuNewToday.
     */
    int getFirstSkuNewToday();

    /**
     * <code>string _rankstr_store_first_sku_new_today = 8;</code>
     * @return The rankstrStoreFirstSkuNewToday.
     */
    String getRankstrStoreFirstSkuNewToday();
    /**
     * <code>string _rankstr_store_first_sku_new_today = 8;</code>
     * @return The bytes for rankstrStoreFirstSkuNewToday.
     */
    com.google.protobuf.ByteString
        getRankstrStoreFirstSkuNewTodayBytes();

    /**
     * <code>int32 _rank_store_first_sku_new_today = 9;</code>
     * @return The rankStoreFirstSkuNewToday.
     */
    int getRankStoreFirstSkuNewToday();

    /**
     * <code>int32 _rank_company_first_sku_new_today = 10;</code>
     * @return The rankCompanyFirstSkuNewToday.
     */
    int getRankCompanyFirstSkuNewToday();

    /**
     * <code>int32 _rank_city_first_sku_new_today = 11;</code>
     * @return The rankCityFirstSkuNewToday.
     */
    int getRankCityFirstSkuNewToday();

    /**
     * <code>int32 _first_sku_new_7days = 12;</code>
     * @return The firstSkuNew7days.
     */
    int getFirstSkuNew7Days();

    /**
     * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
     * @return The rankstrStoreFirstSkuNew7days.
     */
    String getRankstrStoreFirstSkuNew7Days();
    /**
     * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
     * @return The bytes for rankstrStoreFirstSkuNew7days.
     */
    com.google.protobuf.ByteString
        getRankstrStoreFirstSkuNew7DaysBytes();

    /**
     * <code>int32 _rank_store_first_sku_new_7days = 14;</code>
     * @return The rankStoreFirstSkuNew7days.
     */
    int getRankStoreFirstSkuNew7Days();

    /**
     * <code>int32 _rank_company_first_sku_new_7days = 15;</code>
     * @return The rankCompanyFirstSkuNew7days.
     */
    int getRankCompanyFirstSkuNew7Days();

    /**
     * <code>int32 _rank_city_first_sku_new_7days = 16;</code>
     * @return The rankCityFirstSkuNew7days.
     */
    int getRankCityFirstSkuNew7Days();

    /**
     * <code>int32 _first_sku_pm = 17;</code>
     * @return The firstSkuPm.
     */
    int getFirstSkuPm();

    /**
     * <code>string _rankstr_store_first_sku_pm = 18;</code>
     * @return The rankstrStoreFirstSkuPm.
     */
    String getRankstrStoreFirstSkuPm();
    /**
     * <code>string _rankstr_store_first_sku_pm = 18;</code>
     * @return The bytes for rankstrStoreFirstSkuPm.
     */
    com.google.protobuf.ByteString
        getRankstrStoreFirstSkuPmBytes();

    /**
     * <code>int32 _rank_store_first_sku_pm = 19;</code>
     * @return The rankStoreFirstSkuPm.
     */
    int getRankStoreFirstSkuPm();

    /**
     * <code>int32 _rank_company_first_sku_pm = 20;</code>
     * @return The rankCompanyFirstSkuPm.
     */
    int getRankCompanyFirstSkuPm();

    /**
     * <code>int32 _rank_city_first_sku_pm = 21;</code>
     * @return The rankCityFirstSkuPm.
     */
    int getRankCityFirstSkuPm();

    /**
     * <code>string _cal_dt = 22;</code>
     * @return The calDt.
     */
    String getCalDt();
    /**
     * <code>string _cal_dt = 22;</code>
     * @return The bytes for calDt.
     */
    com.google.protobuf.ByteString
        getCalDtBytes();
  }
  /**
   * <pre>
   *message名可以自定义
   * </pre>
   *
   * Protobuf type {@code com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily}
   */
  public static final class da_sanwang_broker_processlog_qhy_rank_daily extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily)
      da_sanwang_broker_processlog_qhy_rank_dailyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use da_sanwang_broker_processlog_qhy_rank_daily.newBuilder() to construct.
    private da_sanwang_broker_processlog_qhy_rank_daily(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private da_sanwang_broker_processlog_qhy_rank_daily() {
      RankstrStoreFirstSkuNewToday_ = "";
      RankstrStoreFirstSkuNew7Days_ = "";
      RankstrStoreFirstSkuPm_ = "";
      CalDt_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new da_sanwang_broker_processlog_qhy_rank_daily();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private da_sanwang_broker_processlog_qhy_rank_daily(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              BrokerId_ = input.readInt64();
              break;
            }
            case 16: {

              StoresId_ = input.readInt32();
              break;
            }
            case 24: {

              RealStoreId_ = input.readInt32();
              break;
            }
            case 32: {

              StoreBrokerNum_ = input.readInt32();
              break;
            }
            case 40: {

              CompanyBrokerNum_ = input.readInt32();
              break;
            }
            case 48: {

              CityBrokerNum_ = input.readInt32();
              break;
            }
            case 56: {

              FirstSkuNewToday_ = input.readInt32();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              RankstrStoreFirstSkuNewToday_ = s;
              break;
            }
            case 72: {

              RankStoreFirstSkuNewToday_ = input.readInt32();
              break;
            }
            case 80: {

              RankCompanyFirstSkuNewToday_ = input.readInt32();
              break;
            }
            case 88: {

              RankCityFirstSkuNewToday_ = input.readInt32();
              break;
            }
            case 96: {

              FirstSkuNew7Days_ = input.readInt32();
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              RankstrStoreFirstSkuNew7Days_ = s;
              break;
            }
            case 112: {

              RankStoreFirstSkuNew7Days_ = input.readInt32();
              break;
            }
            case 120: {

              RankCompanyFirstSkuNew7Days_ = input.readInt32();
              break;
            }
            case 128: {

              RankCityFirstSkuNew7Days_ = input.readInt32();
              break;
            }
            case 136: {

              FirstSkuPm_ = input.readInt32();
              break;
            }
            case 146: {
              String s = input.readStringRequireUtf8();

              RankstrStoreFirstSkuPm_ = s;
              break;
            }
            case 152: {

              RankStoreFirstSkuPm_ = input.readInt32();
              break;
            }
            case 160: {

              RankCompanyFirstSkuPm_ = input.readInt32();
              break;
            }
            case 168: {

              RankCityFirstSkuPm_ = input.readInt32();
              break;
            }
            case 178: {
              String s = input.readStringRequireUtf8();

              CalDt_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DaSanwangBrokerProcesslogQhyRankDaily.internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DaSanwangBrokerProcesslogQhyRankDaily.internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              da_sanwang_broker_processlog_qhy_rank_daily.class, Builder.class);
    }

    public static final int _BROKER_ID_FIELD_NUMBER = 1;
    private long BrokerId_;
    /**
     * <code>int64 _broker_id = 1;</code>
     * @return The brokerId.
     */
    @Override
    public long getBrokerId() {
      return BrokerId_;
    }

    public static final int _STORES_ID_FIELD_NUMBER = 2;
    private int StoresId_;
    /**
     * <code>int32 _stores_id = 2;</code>
     * @return The storesId.
     */
    @Override
    public int getStoresId() {
      return StoresId_;
    }

    public static final int _REAL_STORE_ID_FIELD_NUMBER = 3;
    private int RealStoreId_;
    /**
     * <code>int32 _real_store_id = 3;</code>
     * @return The realStoreId.
     */
    @Override
    public int getRealStoreId() {
      return RealStoreId_;
    }

    public static final int _STORE_BROKER_NUM_FIELD_NUMBER = 4;
    private int StoreBrokerNum_;
    /**
     * <code>int32 _store_broker_num = 4;</code>
     * @return The storeBrokerNum.
     */
    @Override
    public int getStoreBrokerNum() {
      return StoreBrokerNum_;
    }

    public static final int _COMPANY_BROKER_NUM_FIELD_NUMBER = 5;
    private int CompanyBrokerNum_;
    /**
     * <code>int32 _company_broker_num = 5;</code>
     * @return The companyBrokerNum.
     */
    @Override
    public int getCompanyBrokerNum() {
      return CompanyBrokerNum_;
    }

    public static final int _CITY_BROKER_NUM_FIELD_NUMBER = 6;
    private int CityBrokerNum_;
    /**
     * <code>int32 _city_broker_num = 6;</code>
     * @return The cityBrokerNum.
     */
    @Override
    public int getCityBrokerNum() {
      return CityBrokerNum_;
    }

    public static final int _FIRST_SKU_NEW_TODAY_FIELD_NUMBER = 7;
    private int FirstSkuNewToday_;
    /**
     * <code>int32 _first_sku_new_today = 7;</code>
     * @return The firstSkuNewToday.
     */
    @Override
    public int getFirstSkuNewToday() {
      return FirstSkuNewToday_;
    }

    public static final int _RANKSTR_STORE_FIRST_SKU_NEW_TODAY_FIELD_NUMBER = 8;
    private volatile Object RankstrStoreFirstSkuNewToday_;
    /**
     * <code>string _rankstr_store_first_sku_new_today = 8;</code>
     * @return The rankstrStoreFirstSkuNewToday.
     */
    @Override
    public String getRankstrStoreFirstSkuNewToday() {
      Object ref = RankstrStoreFirstSkuNewToday_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        RankstrStoreFirstSkuNewToday_ = s;
        return s;
      }
    }
    /**
     * <code>string _rankstr_store_first_sku_new_today = 8;</code>
     * @return The bytes for rankstrStoreFirstSkuNewToday.
     */
    @Override
    public com.google.protobuf.ByteString
        getRankstrStoreFirstSkuNewTodayBytes() {
      Object ref = RankstrStoreFirstSkuNewToday_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        RankstrStoreFirstSkuNewToday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int _RANK_STORE_FIRST_SKU_NEW_TODAY_FIELD_NUMBER = 9;
    private int RankStoreFirstSkuNewToday_;
    /**
     * <code>int32 _rank_store_first_sku_new_today = 9;</code>
     * @return The rankStoreFirstSkuNewToday.
     */
    @Override
    public int getRankStoreFirstSkuNewToday() {
      return RankStoreFirstSkuNewToday_;
    }

    public static final int _RANK_COMPANY_FIRST_SKU_NEW_TODAY_FIELD_NUMBER = 10;
    private int RankCompanyFirstSkuNewToday_;
    /**
     * <code>int32 _rank_company_first_sku_new_today = 10;</code>
     * @return The rankCompanyFirstSkuNewToday.
     */
    @Override
    public int getRankCompanyFirstSkuNewToday() {
      return RankCompanyFirstSkuNewToday_;
    }

    public static final int _RANK_CITY_FIRST_SKU_NEW_TODAY_FIELD_NUMBER = 11;
    private int RankCityFirstSkuNewToday_;
    /**
     * <code>int32 _rank_city_first_sku_new_today = 11;</code>
     * @return The rankCityFirstSkuNewToday.
     */
    @Override
    public int getRankCityFirstSkuNewToday() {
      return RankCityFirstSkuNewToday_;
    }

    public static final int _FIRST_SKU_NEW_7DAYS_FIELD_NUMBER = 12;
    private int FirstSkuNew7Days_;
    /**
     * <code>int32 _first_sku_new_7days = 12;</code>
     * @return The firstSkuNew7days.
     */
    @Override
    public int getFirstSkuNew7Days() {
      return FirstSkuNew7Days_;
    }

    public static final int _RANKSTR_STORE_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER = 13;
    private volatile Object RankstrStoreFirstSkuNew7Days_;
    /**
     * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
     * @return The rankstrStoreFirstSkuNew7days.
     */
    @Override
    public String getRankstrStoreFirstSkuNew7Days() {
      Object ref = RankstrStoreFirstSkuNew7Days_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        RankstrStoreFirstSkuNew7Days_ = s;
        return s;
      }
    }
    /**
     * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
     * @return The bytes for rankstrStoreFirstSkuNew7days.
     */
    @Override
    public com.google.protobuf.ByteString
        getRankstrStoreFirstSkuNew7DaysBytes() {
      Object ref = RankstrStoreFirstSkuNew7Days_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        RankstrStoreFirstSkuNew7Days_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int _RANK_STORE_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER = 14;
    private int RankStoreFirstSkuNew7Days_;
    /**
     * <code>int32 _rank_store_first_sku_new_7days = 14;</code>
     * @return The rankStoreFirstSkuNew7days.
     */
    @Override
    public int getRankStoreFirstSkuNew7Days() {
      return RankStoreFirstSkuNew7Days_;
    }

    public static final int _RANK_COMPANY_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER = 15;
    private int RankCompanyFirstSkuNew7Days_;
    /**
     * <code>int32 _rank_company_first_sku_new_7days = 15;</code>
     * @return The rankCompanyFirstSkuNew7days.
     */
    @Override
    public int getRankCompanyFirstSkuNew7Days() {
      return RankCompanyFirstSkuNew7Days_;
    }

    public static final int _RANK_CITY_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER = 16;
    private int RankCityFirstSkuNew7Days_;
    /**
     * <code>int32 _rank_city_first_sku_new_7days = 16;</code>
     * @return The rankCityFirstSkuNew7days.
     */
    @Override
    public int getRankCityFirstSkuNew7Days() {
      return RankCityFirstSkuNew7Days_;
    }

    public static final int _FIRST_SKU_PM_FIELD_NUMBER = 17;
    private int FirstSkuPm_;
    /**
     * <code>int32 _first_sku_pm = 17;</code>
     * @return The firstSkuPm.
     */
    @Override
    public int getFirstSkuPm() {
      return FirstSkuPm_;
    }

    public static final int _RANKSTR_STORE_FIRST_SKU_PM_FIELD_NUMBER = 18;
    private volatile Object RankstrStoreFirstSkuPm_;
    /**
     * <code>string _rankstr_store_first_sku_pm = 18;</code>
     * @return The rankstrStoreFirstSkuPm.
     */
    @Override
    public String getRankstrStoreFirstSkuPm() {
      Object ref = RankstrStoreFirstSkuPm_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        RankstrStoreFirstSkuPm_ = s;
        return s;
      }
    }
    /**
     * <code>string _rankstr_store_first_sku_pm = 18;</code>
     * @return The bytes for rankstrStoreFirstSkuPm.
     */
    @Override
    public com.google.protobuf.ByteString
        getRankstrStoreFirstSkuPmBytes() {
      Object ref = RankstrStoreFirstSkuPm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        RankstrStoreFirstSkuPm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int _RANK_STORE_FIRST_SKU_PM_FIELD_NUMBER = 19;
    private int RankStoreFirstSkuPm_;
    /**
     * <code>int32 _rank_store_first_sku_pm = 19;</code>
     * @return The rankStoreFirstSkuPm.
     */
    @Override
    public int getRankStoreFirstSkuPm() {
      return RankStoreFirstSkuPm_;
    }

    public static final int _RANK_COMPANY_FIRST_SKU_PM_FIELD_NUMBER = 20;
    private int RankCompanyFirstSkuPm_;
    /**
     * <code>int32 _rank_company_first_sku_pm = 20;</code>
     * @return The rankCompanyFirstSkuPm.
     */
    @Override
    public int getRankCompanyFirstSkuPm() {
      return RankCompanyFirstSkuPm_;
    }

    public static final int _RANK_CITY_FIRST_SKU_PM_FIELD_NUMBER = 21;
    private int RankCityFirstSkuPm_;
    /**
     * <code>int32 _rank_city_first_sku_pm = 21;</code>
     * @return The rankCityFirstSkuPm.
     */
    @Override
    public int getRankCityFirstSkuPm() {
      return RankCityFirstSkuPm_;
    }

    public static final int _CAL_DT_FIELD_NUMBER = 22;
    private volatile Object CalDt_;
    /**
     * <code>string _cal_dt = 22;</code>
     * @return The calDt.
     */
    @Override
    public String getCalDt() {
      Object ref = CalDt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        CalDt_ = s;
        return s;
      }
    }
    /**
     * <code>string _cal_dt = 22;</code>
     * @return The bytes for calDt.
     */
    @Override
    public com.google.protobuf.ByteString
        getCalDtBytes() {
      Object ref = CalDt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        CalDt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (BrokerId_ != 0L) {
        output.writeInt64(1, BrokerId_);
      }
      if (StoresId_ != 0) {
        output.writeInt32(2, StoresId_);
      }
      if (RealStoreId_ != 0) {
        output.writeInt32(3, RealStoreId_);
      }
      if (StoreBrokerNum_ != 0) {
        output.writeInt32(4, StoreBrokerNum_);
      }
      if (CompanyBrokerNum_ != 0) {
        output.writeInt32(5, CompanyBrokerNum_);
      }
      if (CityBrokerNum_ != 0) {
        output.writeInt32(6, CityBrokerNum_);
      }
      if (FirstSkuNewToday_ != 0) {
        output.writeInt32(7, FirstSkuNewToday_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(RankstrStoreFirstSkuNewToday_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, RankstrStoreFirstSkuNewToday_);
      }
      if (RankStoreFirstSkuNewToday_ != 0) {
        output.writeInt32(9, RankStoreFirstSkuNewToday_);
      }
      if (RankCompanyFirstSkuNewToday_ != 0) {
        output.writeInt32(10, RankCompanyFirstSkuNewToday_);
      }
      if (RankCityFirstSkuNewToday_ != 0) {
        output.writeInt32(11, RankCityFirstSkuNewToday_);
      }
      if (FirstSkuNew7Days_ != 0) {
        output.writeInt32(12, FirstSkuNew7Days_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(RankstrStoreFirstSkuNew7Days_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, RankstrStoreFirstSkuNew7Days_);
      }
      if (RankStoreFirstSkuNew7Days_ != 0) {
        output.writeInt32(14, RankStoreFirstSkuNew7Days_);
      }
      if (RankCompanyFirstSkuNew7Days_ != 0) {
        output.writeInt32(15, RankCompanyFirstSkuNew7Days_);
      }
      if (RankCityFirstSkuNew7Days_ != 0) {
        output.writeInt32(16, RankCityFirstSkuNew7Days_);
      }
      if (FirstSkuPm_ != 0) {
        output.writeInt32(17, FirstSkuPm_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(RankstrStoreFirstSkuPm_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, RankstrStoreFirstSkuPm_);
      }
      if (RankStoreFirstSkuPm_ != 0) {
        output.writeInt32(19, RankStoreFirstSkuPm_);
      }
      if (RankCompanyFirstSkuPm_ != 0) {
        output.writeInt32(20, RankCompanyFirstSkuPm_);
      }
      if (RankCityFirstSkuPm_ != 0) {
        output.writeInt32(21, RankCityFirstSkuPm_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(CalDt_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, CalDt_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (BrokerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, BrokerId_);
      }
      if (StoresId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, StoresId_);
      }
      if (RealStoreId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, RealStoreId_);
      }
      if (StoreBrokerNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, StoreBrokerNum_);
      }
      if (CompanyBrokerNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, CompanyBrokerNum_);
      }
      if (CityBrokerNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, CityBrokerNum_);
      }
      if (FirstSkuNewToday_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, FirstSkuNewToday_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(RankstrStoreFirstSkuNewToday_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, RankstrStoreFirstSkuNewToday_);
      }
      if (RankStoreFirstSkuNewToday_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, RankStoreFirstSkuNewToday_);
      }
      if (RankCompanyFirstSkuNewToday_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, RankCompanyFirstSkuNewToday_);
      }
      if (RankCityFirstSkuNewToday_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, RankCityFirstSkuNewToday_);
      }
      if (FirstSkuNew7Days_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, FirstSkuNew7Days_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(RankstrStoreFirstSkuNew7Days_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, RankstrStoreFirstSkuNew7Days_);
      }
      if (RankStoreFirstSkuNew7Days_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, RankStoreFirstSkuNew7Days_);
      }
      if (RankCompanyFirstSkuNew7Days_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, RankCompanyFirstSkuNew7Days_);
      }
      if (RankCityFirstSkuNew7Days_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, RankCityFirstSkuNew7Days_);
      }
      if (FirstSkuPm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, FirstSkuPm_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(RankstrStoreFirstSkuPm_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, RankstrStoreFirstSkuPm_);
      }
      if (RankStoreFirstSkuPm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, RankStoreFirstSkuPm_);
      }
      if (RankCompanyFirstSkuPm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, RankCompanyFirstSkuPm_);
      }
      if (RankCityFirstSkuPm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, RankCityFirstSkuPm_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(CalDt_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, CalDt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof da_sanwang_broker_processlog_qhy_rank_daily)) {
        return super.equals(obj);
      }
      da_sanwang_broker_processlog_qhy_rank_daily other = (da_sanwang_broker_processlog_qhy_rank_daily) obj;

      if (getBrokerId()
          != other.getBrokerId()) return false;
      if (getStoresId()
          != other.getStoresId()) return false;
      if (getRealStoreId()
          != other.getRealStoreId()) return false;
      if (getStoreBrokerNum()
          != other.getStoreBrokerNum()) return false;
      if (getCompanyBrokerNum()
          != other.getCompanyBrokerNum()) return false;
      if (getCityBrokerNum()
          != other.getCityBrokerNum()) return false;
      if (getFirstSkuNewToday()
          != other.getFirstSkuNewToday()) return false;
      if (!getRankstrStoreFirstSkuNewToday()
          .equals(other.getRankstrStoreFirstSkuNewToday())) return false;
      if (getRankStoreFirstSkuNewToday()
          != other.getRankStoreFirstSkuNewToday()) return false;
      if (getRankCompanyFirstSkuNewToday()
          != other.getRankCompanyFirstSkuNewToday()) return false;
      if (getRankCityFirstSkuNewToday()
          != other.getRankCityFirstSkuNewToday()) return false;
      if (getFirstSkuNew7Days()
          != other.getFirstSkuNew7Days()) return false;
      if (!getRankstrStoreFirstSkuNew7Days()
          .equals(other.getRankstrStoreFirstSkuNew7Days())) return false;
      if (getRankStoreFirstSkuNew7Days()
          != other.getRankStoreFirstSkuNew7Days()) return false;
      if (getRankCompanyFirstSkuNew7Days()
          != other.getRankCompanyFirstSkuNew7Days()) return false;
      if (getRankCityFirstSkuNew7Days()
          != other.getRankCityFirstSkuNew7Days()) return false;
      if (getFirstSkuPm()
          != other.getFirstSkuPm()) return false;
      if (!getRankstrStoreFirstSkuPm()
          .equals(other.getRankstrStoreFirstSkuPm())) return false;
      if (getRankStoreFirstSkuPm()
          != other.getRankStoreFirstSkuPm()) return false;
      if (getRankCompanyFirstSkuPm()
          != other.getRankCompanyFirstSkuPm()) return false;
      if (getRankCityFirstSkuPm()
          != other.getRankCityFirstSkuPm()) return false;
      if (!getCalDt()
          .equals(other.getCalDt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + _BROKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBrokerId());
      hash = (37 * hash) + _STORES_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStoresId();
      hash = (37 * hash) + _REAL_STORE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRealStoreId();
      hash = (37 * hash) + _STORE_BROKER_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getStoreBrokerNum();
      hash = (37 * hash) + _COMPANY_BROKER_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyBrokerNum();
      hash = (37 * hash) + _CITY_BROKER_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getCityBrokerNum();
      hash = (37 * hash) + _FIRST_SKU_NEW_TODAY_FIELD_NUMBER;
      hash = (53 * hash) + getFirstSkuNewToday();
      hash = (37 * hash) + _RANKSTR_STORE_FIRST_SKU_NEW_TODAY_FIELD_NUMBER;
      hash = (53 * hash) + getRankstrStoreFirstSkuNewToday().hashCode();
      hash = (37 * hash) + _RANK_STORE_FIRST_SKU_NEW_TODAY_FIELD_NUMBER;
      hash = (53 * hash) + getRankStoreFirstSkuNewToday();
      hash = (37 * hash) + _RANK_COMPANY_FIRST_SKU_NEW_TODAY_FIELD_NUMBER;
      hash = (53 * hash) + getRankCompanyFirstSkuNewToday();
      hash = (37 * hash) + _RANK_CITY_FIRST_SKU_NEW_TODAY_FIELD_NUMBER;
      hash = (53 * hash) + getRankCityFirstSkuNewToday();
      hash = (37 * hash) + _FIRST_SKU_NEW_7DAYS_FIELD_NUMBER;
      hash = (53 * hash) + getFirstSkuNew7Days();
      hash = (37 * hash) + _RANKSTR_STORE_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER;
      hash = (53 * hash) + getRankstrStoreFirstSkuNew7Days().hashCode();
      hash = (37 * hash) + _RANK_STORE_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER;
      hash = (53 * hash) + getRankStoreFirstSkuNew7Days();
      hash = (37 * hash) + _RANK_COMPANY_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER;
      hash = (53 * hash) + getRankCompanyFirstSkuNew7Days();
      hash = (37 * hash) + _RANK_CITY_FIRST_SKU_NEW_7DAYS_FIELD_NUMBER;
      hash = (53 * hash) + getRankCityFirstSkuNew7Days();
      hash = (37 * hash) + _FIRST_SKU_PM_FIELD_NUMBER;
      hash = (53 * hash) + getFirstSkuPm();
      hash = (37 * hash) + _RANKSTR_STORE_FIRST_SKU_PM_FIELD_NUMBER;
      hash = (53 * hash) + getRankstrStoreFirstSkuPm().hashCode();
      hash = (37 * hash) + _RANK_STORE_FIRST_SKU_PM_FIELD_NUMBER;
      hash = (53 * hash) + getRankStoreFirstSkuPm();
      hash = (37 * hash) + _RANK_COMPANY_FIRST_SKU_PM_FIELD_NUMBER;
      hash = (53 * hash) + getRankCompanyFirstSkuPm();
      hash = (37 * hash) + _RANK_CITY_FIRST_SKU_PM_FIELD_NUMBER;
      hash = (53 * hash) + getRankCityFirstSkuPm();
      hash = (37 * hash) + _CAL_DT_FIELD_NUMBER;
      hash = (53 * hash) + getCalDt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static da_sanwang_broker_processlog_qhy_rank_daily parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(da_sanwang_broker_processlog_qhy_rank_daily prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *message名可以自定义
     * </pre>
     *
     * Protobuf type {@code com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily)
        da_sanwang_broker_processlog_qhy_rank_dailyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DaSanwangBrokerProcesslogQhyRankDaily.internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DaSanwangBrokerProcesslogQhyRankDaily.internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                da_sanwang_broker_processlog_qhy_rank_daily.class, Builder.class);
      }

      // Construct using com.anjuke.trisomic.service.mendian.report.wtable.protobuf.DaSanwangBrokerProcesslogQhyRankDaily.da_sanwang_broker_processlog_qhy_rank_daily.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        BrokerId_ = 0L;

        StoresId_ = 0;

        RealStoreId_ = 0;

        StoreBrokerNum_ = 0;

        CompanyBrokerNum_ = 0;

        CityBrokerNum_ = 0;

        FirstSkuNewToday_ = 0;

        RankstrStoreFirstSkuNewToday_ = "";

        RankStoreFirstSkuNewToday_ = 0;

        RankCompanyFirstSkuNewToday_ = 0;

        RankCityFirstSkuNewToday_ = 0;

        FirstSkuNew7Days_ = 0;

        RankstrStoreFirstSkuNew7Days_ = "";

        RankStoreFirstSkuNew7Days_ = 0;

        RankCompanyFirstSkuNew7Days_ = 0;

        RankCityFirstSkuNew7Days_ = 0;

        FirstSkuPm_ = 0;

        RankstrStoreFirstSkuPm_ = "";

        RankStoreFirstSkuPm_ = 0;

        RankCompanyFirstSkuPm_ = 0;

        RankCityFirstSkuPm_ = 0;

        CalDt_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DaSanwangBrokerProcesslogQhyRankDaily.internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_descriptor;
      }

      @Override
      public da_sanwang_broker_processlog_qhy_rank_daily getDefaultInstanceForType() {
        return da_sanwang_broker_processlog_qhy_rank_daily.getDefaultInstance();
      }

      @Override
      public da_sanwang_broker_processlog_qhy_rank_daily build() {
        da_sanwang_broker_processlog_qhy_rank_daily result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public da_sanwang_broker_processlog_qhy_rank_daily buildPartial() {
        da_sanwang_broker_processlog_qhy_rank_daily result = new da_sanwang_broker_processlog_qhy_rank_daily(this);
        result.BrokerId_ = BrokerId_;
        result.StoresId_ = StoresId_;
        result.RealStoreId_ = RealStoreId_;
        result.StoreBrokerNum_ = StoreBrokerNum_;
        result.CompanyBrokerNum_ = CompanyBrokerNum_;
        result.CityBrokerNum_ = CityBrokerNum_;
        result.FirstSkuNewToday_ = FirstSkuNewToday_;
        result.RankstrStoreFirstSkuNewToday_ = RankstrStoreFirstSkuNewToday_;
        result.RankStoreFirstSkuNewToday_ = RankStoreFirstSkuNewToday_;
        result.RankCompanyFirstSkuNewToday_ = RankCompanyFirstSkuNewToday_;
        result.RankCityFirstSkuNewToday_ = RankCityFirstSkuNewToday_;
        result.FirstSkuNew7Days_ = FirstSkuNew7Days_;
        result.RankstrStoreFirstSkuNew7Days_ = RankstrStoreFirstSkuNew7Days_;
        result.RankStoreFirstSkuNew7Days_ = RankStoreFirstSkuNew7Days_;
        result.RankCompanyFirstSkuNew7Days_ = RankCompanyFirstSkuNew7Days_;
        result.RankCityFirstSkuNew7Days_ = RankCityFirstSkuNew7Days_;
        result.FirstSkuPm_ = FirstSkuPm_;
        result.RankstrStoreFirstSkuPm_ = RankstrStoreFirstSkuPm_;
        result.RankStoreFirstSkuPm_ = RankStoreFirstSkuPm_;
        result.RankCompanyFirstSkuPm_ = RankCompanyFirstSkuPm_;
        result.RankCityFirstSkuPm_ = RankCityFirstSkuPm_;
        result.CalDt_ = CalDt_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof da_sanwang_broker_processlog_qhy_rank_daily) {
          return mergeFrom((da_sanwang_broker_processlog_qhy_rank_daily)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(da_sanwang_broker_processlog_qhy_rank_daily other) {
        if (other == da_sanwang_broker_processlog_qhy_rank_daily.getDefaultInstance()) return this;
        if (other.getBrokerId() != 0L) {
          setBrokerId(other.getBrokerId());
        }
        if (other.getStoresId() != 0) {
          setStoresId(other.getStoresId());
        }
        if (other.getRealStoreId() != 0) {
          setRealStoreId(other.getRealStoreId());
        }
        if (other.getStoreBrokerNum() != 0) {
          setStoreBrokerNum(other.getStoreBrokerNum());
        }
        if (other.getCompanyBrokerNum() != 0) {
          setCompanyBrokerNum(other.getCompanyBrokerNum());
        }
        if (other.getCityBrokerNum() != 0) {
          setCityBrokerNum(other.getCityBrokerNum());
        }
        if (other.getFirstSkuNewToday() != 0) {
          setFirstSkuNewToday(other.getFirstSkuNewToday());
        }
        if (!other.getRankstrStoreFirstSkuNewToday().isEmpty()) {
          RankstrStoreFirstSkuNewToday_ = other.RankstrStoreFirstSkuNewToday_;
          onChanged();
        }
        if (other.getRankStoreFirstSkuNewToday() != 0) {
          setRankStoreFirstSkuNewToday(other.getRankStoreFirstSkuNewToday());
        }
        if (other.getRankCompanyFirstSkuNewToday() != 0) {
          setRankCompanyFirstSkuNewToday(other.getRankCompanyFirstSkuNewToday());
        }
        if (other.getRankCityFirstSkuNewToday() != 0) {
          setRankCityFirstSkuNewToday(other.getRankCityFirstSkuNewToday());
        }
        if (other.getFirstSkuNew7Days() != 0) {
          setFirstSkuNew7Days(other.getFirstSkuNew7Days());
        }
        if (!other.getRankstrStoreFirstSkuNew7Days().isEmpty()) {
          RankstrStoreFirstSkuNew7Days_ = other.RankstrStoreFirstSkuNew7Days_;
          onChanged();
        }
        if (other.getRankStoreFirstSkuNew7Days() != 0) {
          setRankStoreFirstSkuNew7Days(other.getRankStoreFirstSkuNew7Days());
        }
        if (other.getRankCompanyFirstSkuNew7Days() != 0) {
          setRankCompanyFirstSkuNew7Days(other.getRankCompanyFirstSkuNew7Days());
        }
        if (other.getRankCityFirstSkuNew7Days() != 0) {
          setRankCityFirstSkuNew7Days(other.getRankCityFirstSkuNew7Days());
        }
        if (other.getFirstSkuPm() != 0) {
          setFirstSkuPm(other.getFirstSkuPm());
        }
        if (!other.getRankstrStoreFirstSkuPm().isEmpty()) {
          RankstrStoreFirstSkuPm_ = other.RankstrStoreFirstSkuPm_;
          onChanged();
        }
        if (other.getRankStoreFirstSkuPm() != 0) {
          setRankStoreFirstSkuPm(other.getRankStoreFirstSkuPm());
        }
        if (other.getRankCompanyFirstSkuPm() != 0) {
          setRankCompanyFirstSkuPm(other.getRankCompanyFirstSkuPm());
        }
        if (other.getRankCityFirstSkuPm() != 0) {
          setRankCityFirstSkuPm(other.getRankCityFirstSkuPm());
        }
        if (!other.getCalDt().isEmpty()) {
          CalDt_ = other.CalDt_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        da_sanwang_broker_processlog_qhy_rank_daily parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (da_sanwang_broker_processlog_qhy_rank_daily) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long BrokerId_ ;
      /**
       * <code>int64 _broker_id = 1;</code>
       * @return The brokerId.
       */
      @Override
      public long getBrokerId() {
        return BrokerId_;
      }
      /**
       * <code>int64 _broker_id = 1;</code>
       * @param value The brokerId to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerId(long value) {
        
        BrokerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 _broker_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrokerId() {
        
        BrokerId_ = 0L;
        onChanged();
        return this;
      }

      private int StoresId_ ;
      /**
       * <code>int32 _stores_id = 2;</code>
       * @return The storesId.
       */
      @Override
      public int getStoresId() {
        return StoresId_;
      }
      /**
       * <code>int32 _stores_id = 2;</code>
       * @param value The storesId to set.
       * @return This builder for chaining.
       */
      public Builder setStoresId(int value) {
        
        StoresId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _stores_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStoresId() {
        
        StoresId_ = 0;
        onChanged();
        return this;
      }

      private int RealStoreId_ ;
      /**
       * <code>int32 _real_store_id = 3;</code>
       * @return The realStoreId.
       */
      @Override
      public int getRealStoreId() {
        return RealStoreId_;
      }
      /**
       * <code>int32 _real_store_id = 3;</code>
       * @param value The realStoreId to set.
       * @return This builder for chaining.
       */
      public Builder setRealStoreId(int value) {
        
        RealStoreId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _real_store_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRealStoreId() {
        
        RealStoreId_ = 0;
        onChanged();
        return this;
      }

      private int StoreBrokerNum_ ;
      /**
       * <code>int32 _store_broker_num = 4;</code>
       * @return The storeBrokerNum.
       */
      @Override
      public int getStoreBrokerNum() {
        return StoreBrokerNum_;
      }
      /**
       * <code>int32 _store_broker_num = 4;</code>
       * @param value The storeBrokerNum to set.
       * @return This builder for chaining.
       */
      public Builder setStoreBrokerNum(int value) {
        
        StoreBrokerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _store_broker_num = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStoreBrokerNum() {
        
        StoreBrokerNum_ = 0;
        onChanged();
        return this;
      }

      private int CompanyBrokerNum_ ;
      /**
       * <code>int32 _company_broker_num = 5;</code>
       * @return The companyBrokerNum.
       */
      @Override
      public int getCompanyBrokerNum() {
        return CompanyBrokerNum_;
      }
      /**
       * <code>int32 _company_broker_num = 5;</code>
       * @param value The companyBrokerNum to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyBrokerNum(int value) {
        
        CompanyBrokerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _company_broker_num = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompanyBrokerNum() {
        
        CompanyBrokerNum_ = 0;
        onChanged();
        return this;
      }

      private int CityBrokerNum_ ;
      /**
       * <code>int32 _city_broker_num = 6;</code>
       * @return The cityBrokerNum.
       */
      @Override
      public int getCityBrokerNum() {
        return CityBrokerNum_;
      }
      /**
       * <code>int32 _city_broker_num = 6;</code>
       * @param value The cityBrokerNum to set.
       * @return This builder for chaining.
       */
      public Builder setCityBrokerNum(int value) {
        
        CityBrokerNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _city_broker_num = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCityBrokerNum() {
        
        CityBrokerNum_ = 0;
        onChanged();
        return this;
      }

      private int FirstSkuNewToday_ ;
      /**
       * <code>int32 _first_sku_new_today = 7;</code>
       * @return The firstSkuNewToday.
       */
      @Override
      public int getFirstSkuNewToday() {
        return FirstSkuNewToday_;
      }
      /**
       * <code>int32 _first_sku_new_today = 7;</code>
       * @param value The firstSkuNewToday to set.
       * @return This builder for chaining.
       */
      public Builder setFirstSkuNewToday(int value) {
        
        FirstSkuNewToday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _first_sku_new_today = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstSkuNewToday() {
        
        FirstSkuNewToday_ = 0;
        onChanged();
        return this;
      }

      private Object RankstrStoreFirstSkuNewToday_ = "";
      /**
       * <code>string _rankstr_store_first_sku_new_today = 8;</code>
       * @return The rankstrStoreFirstSkuNewToday.
       */
      public String getRankstrStoreFirstSkuNewToday() {
        Object ref = RankstrStoreFirstSkuNewToday_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          RankstrStoreFirstSkuNewToday_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string _rankstr_store_first_sku_new_today = 8;</code>
       * @return The bytes for rankstrStoreFirstSkuNewToday.
       */
      public com.google.protobuf.ByteString
          getRankstrStoreFirstSkuNewTodayBytes() {
        Object ref = RankstrStoreFirstSkuNewToday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          RankstrStoreFirstSkuNewToday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string _rankstr_store_first_sku_new_today = 8;</code>
       * @param value The rankstrStoreFirstSkuNewToday to set.
       * @return This builder for chaining.
       */
      public Builder setRankstrStoreFirstSkuNewToday(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        RankstrStoreFirstSkuNewToday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string _rankstr_store_first_sku_new_today = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankstrStoreFirstSkuNewToday() {
        
        RankstrStoreFirstSkuNewToday_ = getDefaultInstance().getRankstrStoreFirstSkuNewToday();
        onChanged();
        return this;
      }
      /**
       * <code>string _rankstr_store_first_sku_new_today = 8;</code>
       * @param value The bytes for rankstrStoreFirstSkuNewToday to set.
       * @return This builder for chaining.
       */
      public Builder setRankstrStoreFirstSkuNewTodayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        RankstrStoreFirstSkuNewToday_ = value;
        onChanged();
        return this;
      }

      private int RankStoreFirstSkuNewToday_ ;
      /**
       * <code>int32 _rank_store_first_sku_new_today = 9;</code>
       * @return The rankStoreFirstSkuNewToday.
       */
      @Override
      public int getRankStoreFirstSkuNewToday() {
        return RankStoreFirstSkuNewToday_;
      }
      /**
       * <code>int32 _rank_store_first_sku_new_today = 9;</code>
       * @param value The rankStoreFirstSkuNewToday to set.
       * @return This builder for chaining.
       */
      public Builder setRankStoreFirstSkuNewToday(int value) {
        
        RankStoreFirstSkuNewToday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_store_first_sku_new_today = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankStoreFirstSkuNewToday() {
        
        RankStoreFirstSkuNewToday_ = 0;
        onChanged();
        return this;
      }

      private int RankCompanyFirstSkuNewToday_ ;
      /**
       * <code>int32 _rank_company_first_sku_new_today = 10;</code>
       * @return The rankCompanyFirstSkuNewToday.
       */
      @Override
      public int getRankCompanyFirstSkuNewToday() {
        return RankCompanyFirstSkuNewToday_;
      }
      /**
       * <code>int32 _rank_company_first_sku_new_today = 10;</code>
       * @param value The rankCompanyFirstSkuNewToday to set.
       * @return This builder for chaining.
       */
      public Builder setRankCompanyFirstSkuNewToday(int value) {
        
        RankCompanyFirstSkuNewToday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_company_first_sku_new_today = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankCompanyFirstSkuNewToday() {
        
        RankCompanyFirstSkuNewToday_ = 0;
        onChanged();
        return this;
      }

      private int RankCityFirstSkuNewToday_ ;
      /**
       * <code>int32 _rank_city_first_sku_new_today = 11;</code>
       * @return The rankCityFirstSkuNewToday.
       */
      @Override
      public int getRankCityFirstSkuNewToday() {
        return RankCityFirstSkuNewToday_;
      }
      /**
       * <code>int32 _rank_city_first_sku_new_today = 11;</code>
       * @param value The rankCityFirstSkuNewToday to set.
       * @return This builder for chaining.
       */
      public Builder setRankCityFirstSkuNewToday(int value) {
        
        RankCityFirstSkuNewToday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_city_first_sku_new_today = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankCityFirstSkuNewToday() {
        
        RankCityFirstSkuNewToday_ = 0;
        onChanged();
        return this;
      }

      private int FirstSkuNew7Days_ ;
      /**
       * <code>int32 _first_sku_new_7days = 12;</code>
       * @return The firstSkuNew7days.
       */
      @Override
      public int getFirstSkuNew7Days() {
        return FirstSkuNew7Days_;
      }
      /**
       * <code>int32 _first_sku_new_7days = 12;</code>
       * @param value The firstSkuNew7days to set.
       * @return This builder for chaining.
       */
      public Builder setFirstSkuNew7Days(int value) {
        
        FirstSkuNew7Days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _first_sku_new_7days = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstSkuNew7Days() {
        
        FirstSkuNew7Days_ = 0;
        onChanged();
        return this;
      }

      private Object RankstrStoreFirstSkuNew7Days_ = "";
      /**
       * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
       * @return The rankstrStoreFirstSkuNew7days.
       */
      public String getRankstrStoreFirstSkuNew7Days() {
        Object ref = RankstrStoreFirstSkuNew7Days_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          RankstrStoreFirstSkuNew7Days_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
       * @return The bytes for rankstrStoreFirstSkuNew7days.
       */
      public com.google.protobuf.ByteString
          getRankstrStoreFirstSkuNew7DaysBytes() {
        Object ref = RankstrStoreFirstSkuNew7Days_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          RankstrStoreFirstSkuNew7Days_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
       * @param value The rankstrStoreFirstSkuNew7days to set.
       * @return This builder for chaining.
       */
      public Builder setRankstrStoreFirstSkuNew7Days(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        RankstrStoreFirstSkuNew7Days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankstrStoreFirstSkuNew7Days() {
        
        RankstrStoreFirstSkuNew7Days_ = getDefaultInstance().getRankstrStoreFirstSkuNew7Days();
        onChanged();
        return this;
      }
      /**
       * <code>string _rankstr_store_first_sku_new_7days = 13;</code>
       * @param value The bytes for rankstrStoreFirstSkuNew7days to set.
       * @return This builder for chaining.
       */
      public Builder setRankstrStoreFirstSkuNew7DaysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        RankstrStoreFirstSkuNew7Days_ = value;
        onChanged();
        return this;
      }

      private int RankStoreFirstSkuNew7Days_ ;
      /**
       * <code>int32 _rank_store_first_sku_new_7days = 14;</code>
       * @return The rankStoreFirstSkuNew7days.
       */
      @Override
      public int getRankStoreFirstSkuNew7Days() {
        return RankStoreFirstSkuNew7Days_;
      }
      /**
       * <code>int32 _rank_store_first_sku_new_7days = 14;</code>
       * @param value The rankStoreFirstSkuNew7days to set.
       * @return This builder for chaining.
       */
      public Builder setRankStoreFirstSkuNew7Days(int value) {
        
        RankStoreFirstSkuNew7Days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_store_first_sku_new_7days = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankStoreFirstSkuNew7Days() {
        
        RankStoreFirstSkuNew7Days_ = 0;
        onChanged();
        return this;
      }

      private int RankCompanyFirstSkuNew7Days_ ;
      /**
       * <code>int32 _rank_company_first_sku_new_7days = 15;</code>
       * @return The rankCompanyFirstSkuNew7days.
       */
      @Override
      public int getRankCompanyFirstSkuNew7Days() {
        return RankCompanyFirstSkuNew7Days_;
      }
      /**
       * <code>int32 _rank_company_first_sku_new_7days = 15;</code>
       * @param value The rankCompanyFirstSkuNew7days to set.
       * @return This builder for chaining.
       */
      public Builder setRankCompanyFirstSkuNew7Days(int value) {
        
        RankCompanyFirstSkuNew7Days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_company_first_sku_new_7days = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankCompanyFirstSkuNew7Days() {
        
        RankCompanyFirstSkuNew7Days_ = 0;
        onChanged();
        return this;
      }

      private int RankCityFirstSkuNew7Days_ ;
      /**
       * <code>int32 _rank_city_first_sku_new_7days = 16;</code>
       * @return The rankCityFirstSkuNew7days.
       */
      @Override
      public int getRankCityFirstSkuNew7Days() {
        return RankCityFirstSkuNew7Days_;
      }
      /**
       * <code>int32 _rank_city_first_sku_new_7days = 16;</code>
       * @param value The rankCityFirstSkuNew7days to set.
       * @return This builder for chaining.
       */
      public Builder setRankCityFirstSkuNew7Days(int value) {
        
        RankCityFirstSkuNew7Days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_city_first_sku_new_7days = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankCityFirstSkuNew7Days() {
        
        RankCityFirstSkuNew7Days_ = 0;
        onChanged();
        return this;
      }

      private int FirstSkuPm_ ;
      /**
       * <code>int32 _first_sku_pm = 17;</code>
       * @return The firstSkuPm.
       */
      @Override
      public int getFirstSkuPm() {
        return FirstSkuPm_;
      }
      /**
       * <code>int32 _first_sku_pm = 17;</code>
       * @param value The firstSkuPm to set.
       * @return This builder for chaining.
       */
      public Builder setFirstSkuPm(int value) {
        
        FirstSkuPm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _first_sku_pm = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstSkuPm() {
        
        FirstSkuPm_ = 0;
        onChanged();
        return this;
      }

      private Object RankstrStoreFirstSkuPm_ = "";
      /**
       * <code>string _rankstr_store_first_sku_pm = 18;</code>
       * @return The rankstrStoreFirstSkuPm.
       */
      public String getRankstrStoreFirstSkuPm() {
        Object ref = RankstrStoreFirstSkuPm_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          RankstrStoreFirstSkuPm_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string _rankstr_store_first_sku_pm = 18;</code>
       * @return The bytes for rankstrStoreFirstSkuPm.
       */
      public com.google.protobuf.ByteString
          getRankstrStoreFirstSkuPmBytes() {
        Object ref = RankstrStoreFirstSkuPm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          RankstrStoreFirstSkuPm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string _rankstr_store_first_sku_pm = 18;</code>
       * @param value The rankstrStoreFirstSkuPm to set.
       * @return This builder for chaining.
       */
      public Builder setRankstrStoreFirstSkuPm(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        RankstrStoreFirstSkuPm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string _rankstr_store_first_sku_pm = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankstrStoreFirstSkuPm() {
        
        RankstrStoreFirstSkuPm_ = getDefaultInstance().getRankstrStoreFirstSkuPm();
        onChanged();
        return this;
      }
      /**
       * <code>string _rankstr_store_first_sku_pm = 18;</code>
       * @param value The bytes for rankstrStoreFirstSkuPm to set.
       * @return This builder for chaining.
       */
      public Builder setRankstrStoreFirstSkuPmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        RankstrStoreFirstSkuPm_ = value;
        onChanged();
        return this;
      }

      private int RankStoreFirstSkuPm_ ;
      /**
       * <code>int32 _rank_store_first_sku_pm = 19;</code>
       * @return The rankStoreFirstSkuPm.
       */
      @Override
      public int getRankStoreFirstSkuPm() {
        return RankStoreFirstSkuPm_;
      }
      /**
       * <code>int32 _rank_store_first_sku_pm = 19;</code>
       * @param value The rankStoreFirstSkuPm to set.
       * @return This builder for chaining.
       */
      public Builder setRankStoreFirstSkuPm(int value) {
        
        RankStoreFirstSkuPm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_store_first_sku_pm = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankStoreFirstSkuPm() {
        
        RankStoreFirstSkuPm_ = 0;
        onChanged();
        return this;
      }

      private int RankCompanyFirstSkuPm_ ;
      /**
       * <code>int32 _rank_company_first_sku_pm = 20;</code>
       * @return The rankCompanyFirstSkuPm.
       */
      @Override
      public int getRankCompanyFirstSkuPm() {
        return RankCompanyFirstSkuPm_;
      }
      /**
       * <code>int32 _rank_company_first_sku_pm = 20;</code>
       * @param value The rankCompanyFirstSkuPm to set.
       * @return This builder for chaining.
       */
      public Builder setRankCompanyFirstSkuPm(int value) {
        
        RankCompanyFirstSkuPm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_company_first_sku_pm = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankCompanyFirstSkuPm() {
        
        RankCompanyFirstSkuPm_ = 0;
        onChanged();
        return this;
      }

      private int RankCityFirstSkuPm_ ;
      /**
       * <code>int32 _rank_city_first_sku_pm = 21;</code>
       * @return The rankCityFirstSkuPm.
       */
      @Override
      public int getRankCityFirstSkuPm() {
        return RankCityFirstSkuPm_;
      }
      /**
       * <code>int32 _rank_city_first_sku_pm = 21;</code>
       * @param value The rankCityFirstSkuPm to set.
       * @return This builder for chaining.
       */
      public Builder setRankCityFirstSkuPm(int value) {
        
        RankCityFirstSkuPm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 _rank_city_first_sku_pm = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearRankCityFirstSkuPm() {
        
        RankCityFirstSkuPm_ = 0;
        onChanged();
        return this;
      }

      private Object CalDt_ = "";
      /**
       * <code>string _cal_dt = 22;</code>
       * @return The calDt.
       */
      public String getCalDt() {
        Object ref = CalDt_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          CalDt_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string _cal_dt = 22;</code>
       * @return The bytes for calDt.
       */
      public com.google.protobuf.ByteString
          getCalDtBytes() {
        Object ref = CalDt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          CalDt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string _cal_dt = 22;</code>
       * @param value The calDt to set.
       * @return This builder for chaining.
       */
      public Builder setCalDt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        CalDt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string _cal_dt = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearCalDt() {
        
        CalDt_ = getDefaultInstance().getCalDt();
        onChanged();
        return this;
      }
      /**
       * <code>string _cal_dt = 22;</code>
       * @param value The bytes for calDt to set.
       * @return This builder for chaining.
       */
      public Builder setCalDtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        CalDt_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily)
    }

    // @@protoc_insertion_point(class_scope:com.anjuke.trisomic.service.mendian.report.wtable.protobuf.da_sanwang_broker_processlog_qhy_rank_daily)
    private static final da_sanwang_broker_processlog_qhy_rank_daily DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new da_sanwang_broker_processlog_qhy_rank_daily();
    }

    public static da_sanwang_broker_processlog_qhy_rank_daily getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<da_sanwang_broker_processlog_qhy_rank_daily>
        PARSER = new com.google.protobuf.AbstractParser<da_sanwang_broker_processlog_qhy_rank_daily>() {
      @Override
      public da_sanwang_broker_processlog_qhy_rank_daily parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new da_sanwang_broker_processlog_qhy_rank_daily(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<da_sanwang_broker_processlog_qhy_rank_daily> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<da_sanwang_broker_processlog_qhy_rank_daily> getParserForType() {
      return PARSER;
    }

    @Override
    public da_sanwang_broker_processlog_qhy_rank_daily getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n1da_sanwang_broker_processlog_qhy_rank_" +
      "daily.proto\022:com.anjuke.trisomic.service" +
      ".mendian.report.wtable.protobuf\"\377\005\n+da_s" +
      "anwang_broker_processlog_qhy_rank_daily\022" +
      "\022\n\n_broker_id\030\001 \001(\003\022\022\n\n_stores_id\030\002 \001(\005\022" +
      "\026\n\016_real_store_id\030\003 \001(\005\022\031\n\021_store_broker" +
      "_num\030\004 \001(\005\022\033\n\023_company_broker_num\030\005 \001(\005\022" +
      "\030\n\020_city_broker_num\030\006 \001(\005\022\034\n\024_first_sku_" +
      "new_today\030\007 \001(\005\022*\n\"_rankstr_store_first_" +
      "sku_new_today\030\010 \001(\t\022\'\n\037_rank_store_first" +
      "_sku_new_today\030\t \001(\005\022)\n!_rank_company_fi" +
      "rst_sku_new_today\030\n \001(\005\022&\n\036_rank_city_fi" +
      "rst_sku_new_today\030\013 \001(\005\022\034\n\024_first_sku_ne" +
      "w_7days\030\014 \001(\005\022*\n\"_rankstr_store_first_sk" +
      "u_new_7days\030\r \001(\t\022\'\n\037_rank_store_first_s" +
      "ku_new_7days\030\016 \001(\005\022)\n!_rank_company_firs" +
      "t_sku_new_7days\030\017 \001(\005\022&\n\036_rank_city_firs" +
      "t_sku_new_7days\030\020 \001(\005\022\025\n\r_first_sku_pm\030\021" +
      " \001(\005\022#\n\033_rankstr_store_first_sku_pm\030\022 \001(" +
      "\t\022 \n\030_rank_store_first_sku_pm\030\023 \001(\005\022\"\n\032_" +
      "rank_company_first_sku_pm\030\024 \001(\005\022\037\n\027_rank" +
      "_city_first_sku_pm\030\025 \001(\005\022\017\n\007_cal_dt\030\026 \001(" +
      "\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_anjuke_trisomic_service_mendian_report_wtable_protobuf_da_sanwang_broker_processlog_qhy_rank_daily_descriptor,
        new String[] { "BrokerId", "StoresId", "RealStoreId", "StoreBrokerNum", "CompanyBrokerNum", "CityBrokerNum", "FirstSkuNewToday", "RankstrStoreFirstSkuNewToday", "RankStoreFirstSkuNewToday", "RankCompanyFirstSkuNewToday", "RankCityFirstSkuNewToday", "FirstSkuNew7Days", "RankstrStoreFirstSkuNew7Days", "RankStoreFirstSkuNew7Days", "RankCompanyFirstSkuNew7Days", "RankCityFirstSkuNew7Days", "FirstSkuPm", "RankstrStoreFirstSkuPm", "RankStoreFirstSkuPm", "RankCompanyFirstSkuPm", "RankCityFirstSkuPm", "CalDt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
